### PR TITLE
Improved Rain Detector model

### PR DESCRIPTION
**Pull request by ChloeDawn**
This pull request also fixes the display of item model, so it doesn't look as derpy in inventories etc.
I also renamed the rain detector model files to make more logical sense.
Your resource locations are all broken on this branch for 1.11+? I left that as-is though.

Note: If there's anything else you'd like from this PR, just let me know! I was bored, saw your mod, and just wanted to help out. :)

**Screenshots of the improved model:**

Screenshot when not raining
Screenshot when raining

### CODE REVIEW

**Comment by TacoSupremes** [comment]
I really like the new model. It looks so much better in the world now. I was never really a big fan of the old model and I appreciate your contribution.  You said that my resource locations are broken, but I am unsure of what you mean. If you know how to fix them please send me a message.

**Comment by ChloeDawn** [comment]
When I say broken I mean a lot of your assets have capitalized names on the repository. As you may know, lowercased names are enforced in 1.11+ for assets (their resource locations). In your compiled JAR files they are lowercased.. Just not on the repo, for some reason. 😛

**Comment by TacoSupremes** [comment]
Ok, yeah for some reason the repo refuses to change the names to lowercase even though I have changed it multiple times. I have also added your name to the Mcmod file and I will add you to the credits on the curseforge page once I release the next build. Thanks for your help!

**Comment by Tamaized** [comment]
Just a heads up, I get the same casing issue on my repo, the way I solve it is to remove the files in the repo then readd them.

**Comment by TacoSupremes** [comment]
yeah, I just deleted the assets folder and then committed it, and then I copied the assets back and it appears to have fixed the issue

**Pull request merged**
